swagger: "2.0"
info:
  description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker in"
  version: "1.0.0"
  title: "Swagger"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "hoivu@gmail.com"

host: localhost:8080
basePath: "/api/v1"
tags:
- name: "Menu"
  description: "Menu"
schemes:
- "http"
paths:
  /menu:
    post:
      tags:
      - "Menu"
      summary: "Menu to display on front end"
      description: ""
      operationId: "Create menu"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Schema to add a new menu item"
        required: true
        schema:
          $ref: "#/definitions/Menu"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            properties:
              data:
                type: "object"
                $ref: "#/definitions/Menu"
        "400":
          description: "Validation failed"
         
definitions:
  Menu:
    type: "object"
    properties:
      name:
        type: "string"
      title:
        type: "string"
      icon:
        type: "string"
      level:
        type: "number"
      order:
        type: "number"
      
    xml:
      name: "Menu"   
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
